#ifndef INTEGRATE_TASK_4_ERRORS_H
#define INTEGRATE_TASK_4_ERRORS_H

enum class Error {
    NUM_CMD_ARGS_ERR = 1,
    CONFIG_FILE_OPEN_ERR = 2,
    CONFIG_FILE_CONTENT_ERR = 3,
    UNRECOGNIZED_CMD_OPTION = 4,
    FAILED_TO_REACH_DESIRED_ACCURACY = 100
};

#endif //INTEGRATE_TASK_4_ERRORS_H
